launch --title main
launch --title mode sh -c "defaults read -g AppleInterfaceStyle 2>/dev/null && kitty @ set-colors --all --configured ~/.config/kitty/dark.conf || kitty @ set-colors --all --configured ~/.config/kitty/light.conf"
