-- require 'plugins.packer'
require 'plugins.cmd-palette'
require 'plugins.magma'
require 'plugins.jupyter'
require 'plugins.alpha'
require 'plugins.markdown'
require 'plugins.knap'
-- require 'plugins.tree'
-- require 'plugins.icon'
require 'plugins.tele'
require 'plugins.coc'
-- require 'plugins.cmp'
require 'plugins.treesitter'
-- require 'plugins.luasnip'
require 'plugins.ai'
require 'plugins.tex'
require 'plugins.tabout'

-- CSV
vim.g.csv_arrange_align = 'l*'
