require 'plugins.packer'
require 'plugins.cmd-palette'
require 'plugins.magma'
require 'plugins.jupyter'
require 'plugins.alpha'
require 'plugins.markdown'
-- require 'plugins.tree'
require 'plugins.coc'
--require 'plugins.tabout'
-- require 'plugins.cmp'

